[package]
name = "devtools"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ingest-core = { path = "../core" }
pipeline = { path = "../pipeline" }
agents = { path = "../agents" }
