[package]
name = "ops"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
prometheus = "0.13"
ingest-core = { path = "../core" }
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
once_cell = "1"
