[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
ingest-core = { path = "../core" }
crossbeam-queue = "0.3"
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1"
