[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
ingest-core = { path = "../core" }
tokio = { version = "1", features = ["sync", "macros", "rt"] }
tokio-stream = { version = "0.1", features = ["sync"] }
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1"
